# Generated by Django 6.1.1 on 2026-09-05 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("frota", "0001_initial"),
        ("funcionarios", "0001_initial"),
        ("vendas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdemEntrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endereco_destino",
                    models.TextField(verbose_name="Endereço de Entrega"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("separacao", "Em Separação"),
                            ("em_rota", "Em Rota de Entrega"),
                            ("entregue", "Entregue"),
                            ("cancelado", "Cancelada"),
                        ],
                        default="separacao",
                        max_length=20,
                        verbose_name="Status da Entrega",
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "data_saida",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data/Hora de Saída"
                    ),
                ),
                (
                    "data_conclusao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data/Hora de Conclusão"
                    ),
                ),
                (
                    "entregador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entregas",
                        to="funcionarios.funcionario",
                        verbose_name="Entregador/Motorista",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entregas",
                        to="frota.veiculo",
                        verbose_name="Veículo Alocado",
                    ),
                ),
                (
                    "venda",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordem_entrega",
                        to="vendas.venda",
                        verbose_name="Venda Relacionada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordem de Entrega",
                "verbose_name_plural": "Ordens de Entrega",
                "ordering": ["-data_criacao"],
            },
        ),
    ]
