# Generated by Django 6.1.1 on 2026-09-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placa",
                    models.CharField(
                        db_index=True, max_length=10, unique=True, verbose_name="Placa"
                    ),
                ),
                (
                    "modelo",
                    models.CharField(max_length=100, verbose_name="Modelo/Marca"),
                ),
                (
                    "capacidade_kg",
                    models.IntegerField(
                        default=0, verbose_name="Capacidade de Carga (kg)"
                    ),
                ),
                (
                    "disponivel",
                    models.BooleanField(
                        default=True, verbose_name="Disponível para Rota"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Veículo",
                "verbose_name_plural": "Veículos",
                "ordering": ["modelo"],
            },
        ),
    ]
