# Generated by Django 6.1.1 on 2026-09-05 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("caixa", "0001_initial"),
        ("funcionarios", "0001_initial"),
        ("produtos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("dinheiro", "Dinheiro"),
                            ("pix", "PIX"),
                            ("debito", "Cartão de Débito"),
                            ("credito", "Cartão de Crédito"),
                            ("fiado", "Fiado / Conta Cliente"),
                        ],
                        max_length=20,
                        verbose_name="Forma de Pagamento",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Valor Total",
                    ),
                ),
                (
                    "valor_comissao",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Comissão do Vendedor",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "caixa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendas",
                        to="caixa.caixa",
                        verbose_name="Caixa",
                    ),
                ),
                (
                    "operador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Operador do PDV",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="funcionarios.funcionario",
                        verbose_name="Vendedor Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda",
                "verbose_name_plural": "Vendas",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ItemVenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField(verbose_name="Quantidade")),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço Unitário"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Subtotal"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="produtos.produto",
                        verbose_name="Produto",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="vendas.venda",
                        verbose_name="Venda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da Venda",
                "verbose_name_plural": "Itens da Venda",
            },
        ),
    ]
