# Generated by Django 6.1.1 on 2026-09-05 05:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("funcionarios", "0001_initial"),
        ("produtos", "0001_initial"),
        ("vendas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendas",
                to="clientes.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="itemvenda",
            name="preco_unitario",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Preço Unitário (R$)"
            ),
        ),
        migrations.AlterField(
            model_name="itemvenda",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="itens_vendidos",
                to="produtos.produto",
                verbose_name="Produto",
            ),
        ),
        migrations.AlterField(
            model_name="itemvenda",
            name="quantidade",
            field=models.PositiveIntegerField(verbose_name="Quantidade"),
        ),
        migrations.AlterField(
            model_name="itemvenda",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Subtotal (R$)"
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("dinheiro", "Dinheiro"),
                    ("pix", "PIX"),
                    ("debito", "Cartão de Débito"),
                    ("credito", "Cartão de Crédito"),
                    ("fiado", "Fiado / Crédito"),
                ],
                max_length=20,
                verbose_name="Forma de Pagamento",
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="operador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vendas_operadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Operador do Caixa",
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="valor_comissao",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Valor Comissão (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="valor_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Valor Total (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="vendedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vendas_realizadas",
                to="funcionarios.funcionario",
                verbose_name="Vendedor",
            ),
        ),
    ]
