# Generated by Django 6.1.1 on 2026-09-05 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Caixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("aberto", "Aberto"), ("fechado", "Fechado")],
                        default="aberto",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "saldo_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Saldo Inicial",
                    ),
                ),
                (
                    "saldo_atual",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Saldo Atual em Gaveta",
                    ),
                ),
                (
                    "saldo_fechamento_informado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Saldo Contado no Fechamento",
                    ),
                ),
                (
                    "diferenca",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Diferença (Sobra/Falta)",
                    ),
                ),
                (
                    "data_abertura",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data/Hora de Abertura"
                    ),
                ),
                (
                    "data_fechamento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data/Hora de Fechamento"
                    ),
                ),
                (
                    "operador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="caixas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Operador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caixa da Loja",
                "verbose_name_plural": "Caixas da Loja",
                "ordering": ["-data_abertura"],
            },
        ),
        migrations.CreateModel(
            name="MovimentacaoCaixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("suprimento", "Suprimento (Entrada)"),
                            ("sangria", "Sangria (Retirada)"),
                            ("venda", "Venda de Balcão"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição/Motivo"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "caixa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentacoes",
                        to="caixa.caixa",
                        verbose_name="Caixa",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação de Caixa",
                "verbose_name_plural": "Movimentações de Caixa",
            },
        ),
    ]
