# Generated by Django 6.1.1 on 2026-09-05 04:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razao_social",
                    models.CharField(max_length=150, verbose_name="Razão Social"),
                ),
                (
                    "nome_fantasia",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Nome Fantasia",
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(max_length=20, unique=True, verbose_name="CNPJ"),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "endereco",
                    models.TextField(
                        blank=True, null=True, verbose_name="Endereço Completo"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
                "ordering": ["razao_social"],
            },
        ),
        migrations.CreateModel(
            name="PedidoCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("confirmado", "Confirmado"),
                            ("recebido", "Recebido / Entregue"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="rascunho",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Valor Total (R$)",
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_emissao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Emissão"
                    ),
                ),
                (
                    "data_recebimento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Recebimento"
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos_compra",
                        to="compras.fornecedor",
                        verbose_name="Fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de Compra",
                "verbose_name_plural": "Pedidos de Compra",
                "ordering": ["-data_emissao"],
            },
        ),
        migrations.CreateModel(
            name="ItemPedidoCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(verbose_name="Quantidade Comprada"),
                ),
                (
                    "preco_custo_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Preço de Custo Unitário (R$)",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Subtotal (R$)"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_compra",
                        to="produtos.produto",
                        verbose_name="Produto",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="compras.pedidocompra",
                        verbose_name="Pedido de Compra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Pedido de Compra",
                "verbose_name_plural": "Itens do Pedido de Compra",
            },
        ),
    ]
